### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-simulator#445]
Inject something like the https://github.com/livereload/livereload-js and let `helix-simulator` push a feed of updated files (from the fs watcher) to the client

**Comment by kptdobe** [comment]
I do not see the use case yet, apart from CSS reload which is easy to handle with a bookmarklet.
Images, we don't need. LESS, SASS, we don't do yet.

Full reload, maybe for the config (helix-config, fstab) or the content. Well... `hlx up` already tracks for changes (restart the Helix server on change) but also opens a browser window for you, can't it just reload this window in case of a change ?

**Comment by tripodsan** [comment]
well, livereload does more than just reload the window. from my experience when working with react/vue, any change to the JS/CSS (HTL) trigger a rebuild and redeploy to the browser. In constrast to the CSS-reload bookmarklet, this happens on push, and also if you change `<style>...</style>` code in your HTL.

And: it would come out-of-the box :-)

**Comment by tripodsan** [comment]
I'll look into it....

**Comment by kptdobe** [comment]
> from my experience when working with react/vue, any change to the JS/CSS (HTL) trigger a rebuild and redeploy to the browser.
This usually ends up being a full reload because you cannot (and Live Reload has the same issue) reload JS in the majority of the cases. Only CSS (it is really cool) and this can be achieved with the no-cost bookmarklet.

>  if you change `<style>...</style>` code in your HTL
We did not do that yet.

With one identified pb (css hot reload), we are going to build a complex machinery to cover a lot of hypothetical use cases that, for now, we do not have or nobody is asking for. The customer (@davidnuescheler) was happy with the proposed solution.
This is a perfect example on how we should not build software in 2020. But I agree, it would be cool :)
